---
RNG_SEED: -1
MODULE: 'cifar_resnet101'
NUM_WORKERS_PER_GPU: 4
VERSION: 'cifar100_cresnet101_AH50_max_acc_inference'

DATASET:
    DATASET_NAME: 'cifar100_original'
    ROOT_PATH: 'data/cifar-100'
    VAL_SPLIT: 'val'

NETWORK:
    PRETRAINED_MODEL: 'ckpts/cifar100_cresnet101_AH_50_kd_run_1_0.5_5/best.pth'
    PRETRAINED_LOADING_METHOD: 'standard_with_classifier'
    TRAINING_STRATEGY: 'AdditionalHeads'
    NUM_ADDITIONAL_HEADS: 1
    MAIN:
        NUM_CLASS: 100

VAL:
    BATCH_IMAGES: 128
    SHUFFLE: False
