---
RNG_SEED: -1
MODULE: 'cifar_resnet50'
NUM_WORKERS_PER_GPU: 4
VERSION: 'cifar100_cresnet50_from_cresnet101_AH_50_retry'

DATASET:
    DATASET_NAME: 'cifar100_original'
    ROOT_PATH: 'data/cifar-100'
    VAL_SPLIT: 'val'

NETWORK:
    PRETRAINED_MODEL: 'ckpts/cifar100_cresnet101_AH_50/best.pth'
    PRETRAINED_LOADING_METHOD: 'additional_head'
    MAIN:
        NUM_CLASS: 100

VAL:
    BATCH_IMAGES: 128
    SHUFFLE: False
